import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kind and carta challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid grid-rows-[auto,1fr,auto] min-h-screen px-4 container m-auto">
        <header className="leading-[60px] font-bold ">Kin+Carta challenge</header>
        <main className="py-12">{children}</main>
        <footer className="text-center leading-[60px] opacity-80 ">
          With love ❤ Esteban Pastor
        </footer>
      </body>
    </html>
  );
}
